#  Лабораторная работа №1

## Примеры определения типа числовых данных

In [3]:
typeof(3), typeof(3.5), typeof(3/3.55), typeof(sqrt(3+4im)), typeof(pi)

(Int64, Float64, Float64, ComplexF64, Irrational{:π})

In [10]:
1.0/0.0, 1.0/(-0.0), 0.0/0.0 

(Inf, -Inf, NaN)

In [12]:
typeof(1.0/0.0,), typeof(1.0/(-0.0)), typeof(0.0/0.0 )

(Float64, Float64, Float64)

In [14]:
for T in [Int8,Int16,Int32,Int64,Int128,UInt8,UInt16,UInt32,UInt64,UInt128]
    println("$(lpad(T,7)): [$(typemin(T)),$(typemax(T))]")
end

   Int8: [-128,127]
  Int16: [-32768,32767]
  Int32: [-2147483648,2147483647]
  Int64: [-9223372036854775808,9223372036854775807]
 Int128: [-170141183460469231731687303715884105728,170141183460469231731687303715884105727]
  UInt8: [0,255]
 UInt16: [0,65535]
 UInt32: [0,4294967295]
 UInt64: [0,18446744073709551615]
UInt128: [0,340282366920938463463374607431768211455]


## Примеры приведения аргументов к одному типу

In [21]:
Int64(2.0), Char(2), typeof(Char(2))  

(2, '\x02', Char)

In [23]:
convert(Int64, 2.0), convert(Char,2)

(2, '\x02')

In [25]:
typeof(promote(Int8(1), Float16(4.5), Float32(4.1)))

Tuple{Float32, Float32, Float32}

In [29]:
Bool(1), Bool(0)

(true, false)

## Примеры определения функции

In [35]:
function f(x)
    x^2
end

f (generic function with 1 method)

In [37]:
f(4)

16

In [39]:
g(x)=x^2

g (generic function with 1 method)

In [41]:
g(8)

64

## Примеры работы с массивами 

In [44]:
a = [4 7 6]
b = [1, 2, 3]
a[2], b[2]

(7, 2)

In [46]:
a = 1; b = 2; c = 3; d = 4
Am = [a b; c d]

2×2 Matrix{Int64}:
 1  2
 3  4

In [48]:
Am[1,1], Am[1,2], Am[2,1], Am[2,2]

(1, 2, 3, 4)

In [60]:
aa = [1 2]
AA = [1 2; 3 4]
aa*AA*aa'

1×1 Matrix{Int64}:
 27

In [62]:
aa, AA, aa'

([1 2], [1 2; 3 4], [1; 2;;])

## Задания для самостоятельной работы

### 1 Задание

In [107]:
?readlines

search: readlines readline readlink readbytes! readdir lines eachline



```
readlines(io::IO=stdin; keep::Bool=false)
readlines(filename::AbstractString; keep::Bool=false)
```

Read all lines of an I/O stream or a file as a vector of strings. Behavior is equivalent to saving the result of reading [`readline`](@ref) repeatedly with the same arguments and saving the resulting lines as a vector of strings.  See also [`eachline`](@ref) to iterate over the lines without reading them all at once.

# Examples

```jldoctest
julia> write("my_file.txt", "JuliaLang is a GitHub organization.\nIt has many members.\n");

julia> readlines("my_file.txt")
2-element Vector{String}:
 "JuliaLang is a GitHub organization."
 "It has many members."

julia> readlines("my_file.txt", keep=true)
2-element Vector{String}:
 "JuliaLang is a GitHub organization.\n"
 "It has many members.\n"

julia> rm("my_file.txt")
```


In [5]:
# print() и println()
print("Hello, ") 
println("Julia!") 
println("Julia!") 

Hello, Julia!
Julia!


In [2]:
# show()
x = [5,21,3]
show(x)

[5, 21, 3]

In [103]:
# write()
open("test.txt", "w") do f
    write(f, "Это строка, записанная в файл")
end

53

In [119]:
# read()
data_bytes = open("test.txt") do f
    read(f)
end

53-element Vector{UInt8}:
 0xd0
 0xad
 0xd1
 0x82
 0xd0
 0xbe
 0x20
 0xd1
 0x81
 0xd1
 0x82
 0xd1
 0x80
    ⋮
 0x20
 0xd0
 0xb2
 0x20
 0xd1
 0x84
 0xd0
 0xb0
 0xd0
 0xb9
 0xd0
 0xbb

In [105]:
# readline() - чтение одной строки
line = open("test.txt") do f
    readline(f)
end

"Это строка, записанная в файл"

In [87]:
# readlines() - чтение всех строк
lines = open("test.txt") do f
    readlines(f)
end

1-element Vector{String}:
 "Это строка, записанная в файл"

## 2 задание

In [124]:
?parse

search: parse tryparse Base pairs falses parent



```
parse(type, str; base)
```

Parse a string as a number. For `Integer` types, a base can be specified (the default is 10). For floating-point types, the string is parsed as a decimal floating-point number.  `Complex` types are parsed from decimal strings of the form `"R±Iim"` as a `Complex(R,I)` of the requested type; `"i"` or `"j"` can also be used instead of `"im"`, and `"R"` or `"Iim"` are also permitted. If the string does not contain a valid number, an error is raised.

!!! compat "Julia 1.1"
    `parse(Bool, str)` requires at least Julia 1.1.


# Examples

```jldoctest
julia> parse(Int, "1234")
1234

julia> parse(Int, "1234", base = 5)
194

julia> parse(Int, "afc", base = 16)
2812

julia> parse(Float64, "1.2e-3")
0.0012

julia> parse(Complex{Float64}, "3.2e-1 + 4.5im")
0.32 + 4.5im
```

---

```
parse(::Type{Platform}, triplet::AbstractString)
```

Parses a string platform triplet back into a `Platform` object.

---

```
parse(::Type{SimpleColor}, rgb::String)
```

An analogue of `tryparse(SimpleColor, rgb::String)` (which see), that raises an error instead of returning `nothing`.


In [130]:
parse(Float64, "3.14")

3.14

In [134]:
parse(Int, "0987654432")

987654432

## 3 Задание

In [137]:
#сложение
5+4

9

In [139]:
#вычитание
235-12

223

In [141]:
#умножение
4*2

8

In [152]:
#деление
9/4

2.25

In [156]:
#деление с остатком
9%4

1

In [162]:
#возведение в степень
12^2

144

In [164]:
#извлечение корня
sqrt(225)

15.0

In [174]:
#комплексные числа
z = 6 + 8im
abs(z)

10.0

In [176]:
angle(z)

0.9272952180016122

In [180]:
#сравнения и логические операции
10 > 8

true

In [182]:
10 == 8

false

In [184]:
10 != 8

true

In [186]:
!true

false

In [188]:
true&&false

false

## 4 Задание

In [200]:
v1 = [1, 2, 3] #вектор столбец
v2 = [4 5 6] #вектор сторока

1×3 Matrix{Int64}:
 4  5  6

In [204]:
v1 + v1

3-element Vector{Int64}:
 2
 4
 6

In [206]:
v1 - v1

3-element Vector{Int64}:
 0
 0
 0

In [208]:
v1 * 2

3-element Vector{Int64}:
 2
 4
 6

In [210]:
2 * v1

3-element Vector{Int64}:
 2
 4
 6

In [220]:
v1'

1×3 adjoint(::Vector{Int64}) with eltype Int64:
 1  2  3

In [224]:
A = [1 2; 3 4]
B = [5 6; 7 8]

A + B 

2×2 Matrix{Int64}:
  6   8
 10  12

In [226]:
A - B

2×2 Matrix{Int64}:
 -4  -4
 -4  -4

In [228]:
A * B

2×2 Matrix{Int64}:
 19  22
 43  50